export interface ImageAltProcessingState {
  id: string; // Unique ID for React key prop
  url: string; // Original URL or filename
  base64?: string;
  mimeType?: string;
  altText?: string;
  status:
  | 'preview-queued'        // File is queued for client-side preview generation
  | 'preview-loading'       // File is being read for client-side preview
  | 'preview-ready'         // File preview is ready, awaiting 'Generate' click
  | 'pending'               // Queued for processing (either URL or file ready for Gemini)
  | 'loading-image'         // URL image is being fetched
  | 'processing-alt-text'   // Alt text is being generated by Gemini
  | 'completed'             // Alt text generated successfully
  | 'error-image-load'      // Error loading image (from URL or file for preview/processing)
  | 'error-alt-text'        // Error generating alt text from Gemini
  | 'cancelled';            // Processing was cancelled
  errorMessage?: string;
  userModified?: boolean; // True if the alt text was manually edited by the user
  isFileInput?: boolean; // True if this job originated from a file upload
  manualProductContext?: string; // User-defined product context
  showContextInput?: boolean; // To toggle visibility of context input field
  extractedContext?: string; // Context extracted from URL/filename
  selected?: boolean; // For batch actions
  createdAt: number; // Timestamp for creation, useful for sorting and persistence
  // fileObject?: File; // Removed: File objects will be managed outside React state
}

export type ToastType = 'success' | 'error' | 'info' | 'warning';

export interface ToastMessage {
  id: string;
  message: string;
  type: ToastType;
  duration?: number;
}

export type GenerationTone = 'default' | 'seo-focused' | 'brief';

export const ALL_STATUSES: ImageAltProcessingState['status'][] = [
  'preview-queued',
  'preview-loading',
  'preview-ready',
  'pending',
  'loading-image',
  'processing-alt-text',
  'completed',
  'error-image-load',
  'error-alt-text',
  'cancelled'
];

export const STATUS_DISPLAY_NAMES: Record<ImageAltProcessingState['status'] | 'all', string> = {
  'all': 'All Statuses',
  'preview-queued': 'Preview Queued',
  'preview-loading': 'Preview Loading',
  'preview-ready': 'Preview Ready',
  'pending': 'Pending AI',
  'loading-image': 'Loading Image',
  'processing-alt-text': 'Processing Alt Text',
  'completed': 'Completed',
  'error-image-load': 'Error (Image Load)',
  'error-alt-text': 'Error (Alt Text)',
  'cancelled': 'Cancelled',
};